---
# tasks file for ssh
- name: Add new public SSH key to the server
  authorized_key:
    user: ubuntu
    state: present
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOtbz1lUNOXRXw25f5QNF5ae4xj1v2j8r+f7Ap+HkNiP moj-vlastny-kluc"

