---
- name: Server Configuration and Web Deployment
  hosts: tag_Role_app
  become: yes

  roles:
    - role: base
      tags: ["base", "setup"]
    - role: nginx
      tags: ["nginx", "web"]
    - role: app
      tags: ["app", "web"]
    - role: ssh
      tags: ["ssh", "security"]
