---
- hosts: localhost
  connection: local
  tasks:
    - name: Add bastion to known_hosts, so that Ansible can connect to it without prompting for confirmation
      shell: "ssh-keyscan -t ed25519 {{ hostvars['bastion']['ansible_host'] }} >> ~/.ssh/known_hosts"
      changed_when: true

- name: Server Configuration and Web Deployment
  hosts: app_servers
  become: yes

  roles:
    - role: base
      tags: ["base", "setup"]
    - role: nginx
      tags: ["nginx", "web"]
    - role: app
      tags: ["app", "web"]
    - role: ssh
      tags: ["ssh", "security"]